### PR TITLE
Add RectPainter sample

### PR DESCRIPTION
**Pull request by david-c14**
## What does the pull request do?
Adds a new sample. A simple graphics editing tool as a demonstration of live interaction between mouse, offscreen image, and rendering

**Scope of this PR:**
- [ ] fix or update to an existing sample
- [x] add a new sample

## Checklist

**If this is a new Sample**
- [x] Added a ReadMe-file
- [x] Updated the landing page
- [ ] Consider submitting a PR to https://github.com/AvaloniaUI/Documentation with a link to your sample in the related documentation page

**In any case**
- [x] Spell-checking done
- [x] Checked if all hyperlinks work
- [x] Checked if all images are visible

### CODE REVIEW

**Comment by david-c14** [comment]
@dotnet-policy-service agree

**Comment by david-c14** [comment]
I need to implement a graphics editing tool in AvaloniaUI, and came looking for a sample to get me started.  But I couldn't see anything particularly close.  So I built a simple test example to try out what I was doing, and having got it to work, I thought I should submit it back as a sample to fill the gap.

**Comment by maxkatz6** [comment]
Thank you! Sample like this is what I wanted to add for a while now. I am going to review on this week.

**Review by maxkatz6 — APPROVED** [review]
Took me longer to get there, but this PR looks good to me.
Thank you!

**Pull request merged**
